### ISSUE TITLE
publisher address not found

### ISSUE THREAD

**Issue by naqunmiemie** [thirdweb-dev/dashboard#694]
Do I have to configure all the variables in .env?
![image](https://user-images.githubusercontent.com/45996643/205244085-20240ceb-7db8-47bc-9614-c1b9574e121a.png)
![image](https://user-images.githubusercontent.com/45996643/205244321-6477f6b5-a8fd-4aa4-9e1d-2cf7373c65f0.png)
I want to deploy the contract on GOERLI.
![image](https://user-images.githubusercontent.com/45996643/205244596-1fb35c60-55dd-4373-a87e-da8c7d2038de.png)
when I click `Deploy new contract`,an error has occurred.
![image](https://user-images.githubusercontent.com/45996643/205244881-e2eeb8e4-1719-4915-84ff-16541a44cde1.png)
![image](https://user-images.githubusercontent.com/45996643/205244965-53563264-bf2a-4bad-af28-0fa6bc4f8fd9.png)

**Comment by jnsdls** [comment]
the `SSR_ALCHEMY_KEY` is an alchemy.com key that is not restricted to a specific domain (that's why there is a split in this case between SSR and NEXT_PUBLIC) (SSR = only during server side rendering)

I'm not sure what's going on with your version based on your feedback so far. I think the easiest way to help figure it out would be if you could share a link to your forked repo and I can take a look at it that way.

**Comment by jnsdls** [comment]
hi @naqunmiemie - I've just merged PR #733 which massively simplifies (and documents) the .env variables (inside `.env.example` directly)

In addition the project should no longer require any `.env` vars at all to work as a basic build. - If you update your fork to the latest `main` I'm hopeful this will resolve your issue.
